const valid = [
  '',
	'0','1','2','3','4','5','6','7','8','9',
	'0⃣','1⃣','2⃣','3⃣','4⃣','5⃣','6⃣','7⃣','8⃣','9⃣',
  '00', '10', '15', '20', '25', '30', '40', '45', '50',
  '60', '70', '80', '90', '100',
  '0⃣0⃣','1⃣0⃣','1⃣5⃣','2⃣0⃣','2⃣5⃣','3⃣0⃣','3⃣5⃣','4⃣0⃣','4⃣5⃣','5⃣0⃣','5⃣5⃣',
 	'6⃣0⃣','7⃣0⃣','8⃣0⃣','9⃣0⃣','1⃣0⃣0⃣',
	'▶️⃣1⏹️',
	'▶️⃣ 1 ⏹️',
	'▶️⃣1⃣⏹️',
	'▶️⃣2⃣⏹️',
	'▶️⃣10⏹️',
	'▶️⃣ 10 ⏹️',
	'▶️⃣1⃣0⃣⏹️',
	'▶️⃣ 1⃣0⃣ ⏹️',
	'▶️⃣""⏹️',
	"▶️⃣''⏹️",
  '⬜',
	'▶️⃣⬜⏹️',
  ':start:⬜⏹️',
  ':start:⬜ ⏹️',
	'▶️⃣⬜:stop:',
	'▶️⃣⬜:stop:',
	'▶️⃣ ⬜⬜:stop:',
	'👋🏽',
	'👋',
	'▶️⃣👋🏽⏹️',
  ':start::hello::stop:',
  ':start: :hello: :stop:',
  ':start: :hello: :hello: :stop:',
  ':start: :hello: :world: :stop:',
	'▶️⃣👋🏽👋🏽⏹️',
	'▶️⃣👋🏽 👋🏽⏹️',
	'▶️⃣ 👋🏽 👋🏽 ⏹️',
	'▶️⃣👋🏽👋🏽👋🏽⏹️',
	'▶️⃣👋🏽👋🏽⏹️',
	'▶️⃣🌐🌐⏹️',
	'▶️⃣👋🏽🌐👋🏽🌐👋🏽🌐⏹️',
	'▶️⃣👋🏽🌐👋🏽🌐1⃣0⃣👋🏽🌐👋🏽🌐⏹️',
	'👋🏽🌐',
	':hello: :world:',
	'💬',
  ':say:',
	'💬👋🏽',
	'💬🌐',
	'💬👋🏽🌐',
	'▶️⃣💬👋🏽⏹️',
  '▶️⃣💬👋🏽💬🌐⏹️',
  '▶️⃣💬👋🏽🌐⏹️',
	'▶️⃣💬👋🏽🌐⏹️',
  ':say: :hello: :world:',
	'▶️⃣💬👋🏽🌐⏹️',
  '"hello"',
  "'hello'",
  '"hello world"',
  "'hello world'",
	'"iñtërnâtiônàlizætiøn"',
	"'iñtërnâtiônàlizætiøn'",
  '"yo"',
	'💬 "hello world"',
	':say: "hello world"',
	'💬 1',
	'💬 1 2 3',
	'💬 "1 2 3"',
	"💬 '1 2 1'",
 	'💬 "Play is the highest form of research. - Albert Einstein"',
 	'💬 "There are no rules here--we\'re trying to accomplish something. - Thomas Edison"',
 	'💬 "The most dangerous phrase in the language is, \'We\'ve always done it this way.\' - Grace Hopper"',
 	'💬 "A good painting to me has always been like a friend. It keeps me company, comforts and inspires. - Hedy Lamarr"',
	'💬 "It always seems impossible until it\'s done. - Nelson Mandela"',
 	'💬 "There was no choice but to be pioneers. - Margaret Hamilton"',
 	'💬 "The walls between art and engineering exist only in our minds - Theo Jansen"',
 	'💬 "If you get, give. If you learn, teach. - Maya Angelou"',
 	'💬 "Invention, it must be humbly admitted, does not consist in creating out of void, but out of chaos. - Mary Shelley"',
	'💬 "Be regular and orderly in your life, so that you may be violent and original in your work. - Gustave Flaubert"',
	'💬 ""',
	"💬 ''",
	'▶️⃣💬1⃣⏹️',
	'▶️⃣💬1⏹️',
	"▶️⃣💬'1'⏹️",
	'▶️⃣💬"1"⏹️',
	"▶️⃣💬''⏹️",
	'▶️⃣💬""⏹️',
	'▶️⃣ :say: 1 ⏹️',
  '▶️⃣:say:"."⏹️',
  '▶️⃣💬"Hello, World!"⏹️',
  '▶️⃣"Hello, World!"⏹️',
  '▶️⃣"123 - 456"⏹️',
	'▶️⃣💬3⃣💬6⃣💬3⃣⏹️',
	'▶️⃣👋🏽🌐⏹️',
	// Escaped quotes:
	'▶️⃣"💡"⏹️',
	"▶️⃣'💡'⏹️",
	"▶️⃣'💡\"💡'⏹️",
	"▶️⃣'💡\\'💡'⏹️",
	'▶️⃣"💡\'💡"⏹️',
	'▶️⃣"💡\\"💡"⏹️',
	// World languages
	'▶️⃣"你好，世界"⏹️',							// Chinese
  '▶️⃣"ওহে বিশ্ব!"⏹️',             	// Bangla
  '▶️⃣"Hello, World!"⏹️',        // English
	'▶️⃣"Bonjour le monde!"⏹️',		 // French
	'▶️⃣"Hallo Welt!"⏹️',		 			 // German
	'▶️⃣"नमस्ते दुनिया!"⏹️',		 			  // Hindi
	'▶️⃣"こんにちは世界！"⏹️',			  // Japanese
	'▶️⃣"안녕, 세상!"⏹️',			  		 // Korean
	'▶️⃣"Olá Mundo!"⏹️',			  	 // Portuguese
	'▶️⃣"ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!"⏹️',		// Punjabi
	'▶️⃣"Привет мир!"⏹️',				 	 // Russian
	'▶️⃣"¡Hola Mundo!"⏹️',				 // Spanish
	// World languages - Right-to-left
	'⏹️🌐👋🏽◀️⃣',
  '⏹️"!"💬◀️⃣',
	'⏹️"' + '!' + "مرحبا يا عالم" + '"💬◀️⃣',  // Arabic ( Credit: nasser. https://github.com/nasser/--- )
	'⏹️"' + '!' + "שלום עולם" + '"💬◀️⃣',		// Hebrew
	'⏹️"' + '!' + "שלום עולם" + '"◀️⃣',		// Hebrew
  '"🃟"'
]

module.exports = valid
